"""
Stream JSON Parser for Claude Agent Manager

This module provides parsing and processing of Claude Code CLI's stream-json output format.
It handles multi-line JSON chunks, extracts session information, tracks usage statistics,
and emits events for real-time monitoring of agent sessions.

The parser processes several message types from the Claude Code CLI:
- system:init - Session initialization with session_id and available slash commands
- assistant - Streaming message chunks and tool usage
- result - Final response from the agent
- Usage data - Token consumption and cost tracking

Usage:
    >>> emitter = EventEmitter()
    >>> parser = StreamJsonParser(session_id="test", emitter=emitter, emit_streaming_chunks=True)
    >>>
    >>> # Process output line by line
    >>> async for line in process.stdout:
    >>>     parsed = await parser.process_line(line)
    >>>     if parsed:
    >>>         print(f"Received: {parsed.type}")
    >>>
    >>> # Get final usage stats
    >>> usage = parser.usage
    >>> print(f"Total cost: ${usage.total_cost_usd:.4f}")
"""

import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from claude_agent_manager.core.events import Event, EventEmitter, EventType


@dataclass
class UsageStats:
    """
    Token usage and cost statistics for Claude API calls.

    Tracks both input/output tokens and cache-related tokens for accurate
    cost calculation and usage monitoring.

    Attributes:
        input_tokens: Number of input tokens sent to the model
        output_tokens: Number of output tokens generated by the model
        cache_read_tokens: Number of tokens read from cache (discounted cost)
        cache_creation_tokens: Number of tokens written to cache
        total_cost_usd: Cumulative cost in USD for the session
        context_window: Model's maximum context window size (default: 200k)

    Examples:
        >>> stats = UsageStats(input_tokens=1500, output_tokens=500)
        >>> stats.total_cost_usd = 0.025
    """
    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_tokens: int = 0
    cache_creation_tokens: int = 0
    total_cost_usd: float = 0.0
    context_window: int = 200000

    def to_dict(self) -> Dict[str, Any]:
        """Convert usage stats to dictionary format."""
        return {
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "cache_read_tokens": self.cache_read_tokens,
            "cache_creation_tokens": self.cache_creation_tokens,
            "total_cost_usd": self.total_cost_usd,
            "context_window": self.context_window,
        }


@dataclass
class ParsedMessage:
    """
    Parsed message from Claude Code CLI stream-json output.

    Represents a single parsed event from the CLI, which could be a system
    initialization, assistant message, tool call, or result.

    Attributes:
        type: Message type (e.g., "system:init", "assistant", "result")
        subtype: Optional message subtype for finer categorization
        session_id: Claude session identifier (extracted from system:init)
        result: Final result text (for result messages)
        message: Full message data including content and metadata
        usage: Token usage statistics (if usage data present)
        slash_commands: List of available slash commands (from system:init)
        tool_use: Tool call information (name, args, etc.)
        raw: Raw JSON data for the message

    Examples:
        >>> # Session initialization message
        >>> ParsedMessage(
        ...     type="system:init",
        ...     session_id="session_123",
        ...     slash_commands=["/help", "/clear"]
        ... )
        >>>
        >>> # Assistant message with tool use
        >>> ParsedMessage(
        ...     type="assistant",
        ...     tool_use={"name": "Read", "args": {"file_path": "/tmp/test.txt"}},
        ...     raw={...}
        ... )
    """
    type: str
    subtype: Optional[str] = None
    session_id: Optional[str] = None
    result: Optional[str] = None
    message: Optional[Dict[str, Any]] = None
    usage: Optional[UsageStats] = None
    slash_commands: List[str] = field(default_factory=list)
    tool_use: Optional[Dict[str, Any]] = None
    raw: Dict[str, Any] = field(default_factory=dict)


class StreamJsonParser:
    """
    Parser for Claude Code CLI's stream-json output format.

    Processes multi-line JSON chunks from the Claude Code CLI, extracting session
    information, tracking usage statistics, and emitting events for real-time
    monitoring.

    The parser maintains an internal buffer for incomplete JSON lines and tracks
    cumulative usage across the session. It can optionally emit events for
    streaming chunks, tool calls, and usage updates.

    Attributes:
        claude_session_id: The active Claude session ID (extracted from system:init)
        usage: Cumulative usage statistics for the session

    Examples:
        >>> emitter = EventEmitter()
        >>>
        >>> # Register event handlers
        >>> @emitter.on(EventType.SESSION_STARTED)
        >>> async def on_session_start(event: Event):
        ...     print(f"Session started: {event.session_id}")
        >>>
        >>> @emitter.on(EventType.MESSAGE_CHUNK)
        >>> async def on_chunk(event: Event):
        ...     print(event.data["chunk"], end="", flush=True)
        >>>
        >>> # Create parser
        >>> parser = StreamJsonParser(
        ...     session_id="test_session",
        ...     emitter=emitter,
        ...     emit_streaming_chunks=True
        ... )
        >>>
        >>> # Process CLI output
        >>> async for line in process.stdout:
        ...     parsed = await parser.process_line(line)
        ...
        >>> # Get final stats
        >>> print(f"Total tokens: {parser.usage.input_tokens + parser.usage.output_tokens}")
    """

    def __init__(
        self,
        session_id: str,
        emitter: Optional[EventEmitter] = None,
        emit_streaming_chunks: bool = False
    ):
        """
        Initialize the stream JSON parser.

        Args:
            session_id: User-provided session identifier for tracking
            emitter: Optional EventEmitter for emitting parsed events
            emit_streaming_chunks: If True, emit MESSAGE_CHUNK events for streaming text
        """
        self._session_id = session_id
        self._claude_session_id: Optional[str] = None
        self._emitter = emitter
        self._emit_streaming_chunks = emit_streaming_chunks
        self._usage = UsageStats()
        self._buffer = ""

    @property
    def claude_session_id(self) -> Optional[str]:
        """
        Get the Claude-assigned session ID.

        Returns:
            The session ID extracted from system:init message, or None if not yet available
        """
        return self._claude_session_id

    @property
    def usage(self) -> UsageStats:
        """
        Get cumulative usage statistics for the session.

        Returns:
            UsageStats object with token counts and cost
        """
        return self._usage

    async def process_chunk(self, chunk: str) -> List[ParsedMessage]:
        """
        Process a multi-line chunk from the CLI output.

        Handles chunks that may contain multiple complete or incomplete JSON lines.
        Buffers incomplete lines for later processing.

        Args:
            chunk: Raw text chunk from the CLI (may contain multiple lines)

        Returns:
            List of parsed messages (may be empty if no complete messages)

        Examples:
            >>> chunk = '{"type": "system:init", "session_id": "abc"}\\n{"type": "assistant"'
            >>> messages = await parser.process_chunk(chunk)
            >>> len(messages)  # Only first line is complete
            1
        """
        messages: List[ParsedMessage] = []

        # Split chunk into lines and process
        lines = chunk.split('\n')

        for i, line in enumerate(lines):
            # For all lines except the last, add any buffered content
            if i < len(lines) - 1:
                full_line = self._buffer + line
                self._buffer = ""

                if full_line.strip():
                    parsed = await self.process_line(full_line)
                    if parsed:
                        messages.append(parsed)
            else:
                # Last line might be incomplete, add to buffer
                self._buffer += line

        return messages

    async def process_line(self, line: str) -> Optional[ParsedMessage]:
        """
        Process a single line of JSON output.

        Parses the JSON, handles different message types, updates usage statistics,
        and emits appropriate events.

        Args:
            line: Single line of JSON text

        Returns:
            ParsedMessage if the line was valid JSON, None otherwise

        Message Types Handled:
            - system:init: Extracts session_id and slash_commands, emits SESSION_STARTED
            - assistant: Handles streaming chunks and tool_use, emits MESSAGE_CHUNK and TOOL_CALLED
            - result: Extracts final response, emits MESSAGE_RECEIVED
            - Usage data: Updates stats, emits USAGE_UPDATE

        Examples:
            >>> line = '{"type": "system:init", "session_id": "abc123", "slash_commands": ["/help"]}'
            >>> parsed = await parser.process_line(line)
            >>> parsed.session_id
            'abc123'
        """
        line = line.strip()
        if not line:
            return None

        try:
            data = json.loads(line)
            return await self._handle_message(data)
        except json.JSONDecodeError:
            # Invalid JSON, skip
            return None

    async def _handle_message(self, data: Dict[str, Any]) -> ParsedMessage:
        """
        Handle a parsed JSON message and emit appropriate events.

        Processes different message types, extracts relevant information,
        updates internal state, and emits events for listeners.

        Args:
            data: Parsed JSON object

        Returns:
            ParsedMessage with extracted information

        Emitted Events:
            - SESSION_STARTED: When system:init is received
            - MESSAGE_CHUNK: For streaming text (if emit_streaming_chunks=True)
            - TOOL_CALLED: When assistant uses a tool
            - MESSAGE_RECEIVED: When final result is received
            - USAGE_UPDATE: When usage data is present
        """
        msg_type = data.get("type", "unknown")
        msg_subtype = data.get("subtype")
        parsed = ParsedMessage(type=msg_type, subtype=msg_subtype, raw=data)

        # Handle system init - extract session ID and slash commands
        # Format: {"type": "system", "subtype": "init", "session_id": "...", ...}
        if msg_type == "system" and msg_subtype == "init":
            self._claude_session_id = data.get("session_id")
            parsed.session_id = self._claude_session_id
            parsed.slash_commands = data.get("slash_commands", [])

            # Emit SESSION_STARTED event
            if self._emitter:
                event = Event(
                    type=EventType.SESSION_STARTED,
                    session_id=self._session_id,
                    data={
                        "claude_session_id": self._claude_session_id,
                        "slash_commands": parsed.slash_commands,
                    }
                )
                await self._emitter.emit(event)

        # Handle assistant messages - streaming chunks and tool use
        elif msg_type == "assistant":
            message_data = data.get("message", {})
            parsed.message = message_data

            # Check for streaming text content
            if self._emit_streaming_chunks and message_data:
                content = message_data.get("content", [])
                for item in content:
                    if isinstance(item, dict) and item.get("type") == "text":
                        text = item.get("text", "")
                        if text and self._emitter:
                            event = Event(
                                type=EventType.MESSAGE_CHUNK,
                                session_id=self._session_id,
                                data={"chunk": text}
                            )
                            await self._emitter.emit(event)

            # Check for tool use
            if message_data:
                content = message_data.get("content", [])
                for item in content:
                    if isinstance(item, dict) and item.get("type") == "tool_use":
                        parsed.tool_use = {
                            "id": item.get("id"),
                            "name": item.get("name"),
                            "input": item.get("input", {}),
                        }

                        # Emit TOOL_CALLED event
                        if self._emitter:
                            event = Event(
                                type=EventType.TOOL_CALLED,
                                session_id=self._session_id,
                                data={
                                    "tool_id": parsed.tool_use["id"],
                                    "tool": parsed.tool_use["name"],
                                    "args": parsed.tool_use["input"],
                                }
                            )
                            await self._emitter.emit(event)

        # Handle result - final response
        elif msg_type == "result":
            parsed.result = data.get("result", "")

            # Emit MESSAGE_RECEIVED event
            if self._emitter:
                event = Event(
                    type=EventType.MESSAGE_RECEIVED,
                    session_id=self._session_id,
                    data={"content": parsed.result}
                )
                await self._emitter.emit(event)

        # Update usage statistics if present
        self._update_usage(data)
        if data.get("usage") or data.get("modelUsage"):
            parsed.usage = UsageStats(**{
                k: v for k, v in self._usage.to_dict().items()
            })

            # Emit USAGE_UPDATE event
            if self._emitter:
                event = Event(
                    type=EventType.USAGE_UPDATE,
                    session_id=self._session_id,
                    data=parsed.usage.to_dict()
                )
                await self._emitter.emit(event)

        return parsed

    def _update_usage(self, data: Dict[str, Any]) -> None:
        """
        Update cumulative usage statistics from message data.

        Extracts token counts from the usage field and adds them to the
        running totals. Handles both direct usage fields and nested usage objects.

        Args:
            data: Parsed JSON message that may contain usage information

        Examples:
            >>> data = {
            ...     "usage": {
            ...         "input_tokens": 100,
            ...         "output_tokens": 50,
            ...         "cache_read_tokens": 500
            ...     }
            ... }
            >>> parser._update_usage(data)
            >>> parser.usage.input_tokens
            100
        """
        # Check for direct usage field (standard format)
        usage = data.get("usage")
        if usage:
            self._usage.input_tokens += usage.get("input_tokens", 0)
            self._usage.output_tokens += usage.get("output_tokens", 0)
            self._usage.cache_read_tokens += usage.get("cache_read_tokens", 0)
            self._usage.cache_creation_tokens += usage.get("cache_creation_tokens", 0)

        # Check for modelUsage field (aggregate format)
        model_usage = data.get("modelUsage")
        if model_usage:
            for model_stats in model_usage.values():
                if isinstance(model_stats, dict):
                    self._usage.input_tokens += model_stats.get("inputTokens", 0)
                    self._usage.output_tokens += model_stats.get("outputTokens", 0)
                    self._usage.cache_read_tokens += model_stats.get("cacheReadInputTokens", 0)
                    self._usage.cache_creation_tokens += model_stats.get("cacheCreationInputTokens", 0)
                    self._usage.context_window = max(
                        self._usage.context_window,
                        model_stats.get("contextWindow", 200000)
                    )

        # Update cost if present
        if "total_cost_usd" in data:
            self._usage.total_cost_usd = data["total_cost_usd"]

    async def flush(self) -> Optional[ParsedMessage]:
        """
        Flush any remaining buffered data and process it.

        Should be called when the stream ends to ensure any incomplete
        JSON in the buffer is processed.

        Returns:
            ParsedMessage if buffer contained valid JSON, None otherwise

        Examples:
            >>> # Process final buffered content
            >>> final_message = await parser.flush()
            >>> if final_message:
            ...     print(f"Final message: {final_message.type}")
        """
        if not self._buffer.strip():
            return None

        buffered = self._buffer
        self._buffer = ""
        return await self.process_line(buffered)
